const { withProjectBuildGradle } = require('expo/config-plugins');

const MARKER = '// >>> quietloom: git-bash-path';

// react-native-audio-api fetches its prebuilt native binaries from a bash script,
// and on Windows its build.gradle runs that script through Git's bash.exe by
// absolute path. That bash inherits the Windows PATH, which carries Git's `cmd`
// directory but not `usr\bin` — so mkdir, rm and find are not on it. The script
// dies with "mkdir: command not found", exits 127, and takes the whole build with
// it, even when the binaries are already unpacked and there is nothing to fetch.
//
// The launcher you normally start Git Bash with is what puts `usr\bin` on PATH; a
// non-interactive `bash script.sh` never gets it. So put it there for the task.
//
// This has to be injected rather than written by hand because android/ is
// generated by `npx expo prebuild` and any edit there is discarded on the next run.
const SNIPPET = `
${MARKER} <<<
// Windows-only. See plugins/withWindowsGitBashPath.js for why this is here.
if (System.getProperty('os.name').toLowerCase().contains('windows')) {
  subprojects { subproject ->
    if (subproject.name != 'react-native-audio-api') return

    subproject.afterEvaluate {
      def download = subproject.tasks.findByName('downloadPrebuiltBinaries')
      if (!(download instanceof Exec)) return

      // Take the directory from the very bash.exe the task is about to run, so a
      // non-default Git install (or an upstream change of heart) stays correct.
      def bashBin = download.commandLine ? new File(download.commandLine[0] as String).parentFile : null
      if (bashBin == null || !bashBin.isDirectory()) return

      // Reuse the inherited key verbatim: Windows environment variables are
      // case-insensitive, Gradle's environment map is not, and adding 'PATH'
      // alongside an inherited 'Path' leaves the child reading whichever it likes.
      def key = download.environment.keySet().find { it.equalsIgnoreCase('PATH') } ?: 'PATH'
      download.environment key, bashBin.absolutePath + File.pathSeparator + download.environment[key]
    }
  }
}
// <<< quietloom: git-bash-path
`;

/** @type {import('expo/config-plugins').ConfigPlugin} */
const withWindowsGitBashPath = (config) =>
  withProjectBuildGradle(config, (config) => {
    if (config.modResults.language !== 'groovy') {
      throw new Error(
        `withWindowsGitBashPath expected a Groovy android/build.gradle, got ${config.modResults.language}`,
      );
    }

    // prebuild without --clean re-applies mods over the existing file.
    if (!config.modResults.contents.includes(MARKER)) {
      config.modResults.contents += SNIPPET;
    }

    return config;
  });

module.exports = withWindowsGitBashPath;
